CREATE DATABASE Academy;

GO

USE Academy;

GO

CREATE TABLE Faculties(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    Name NVARCHAR(100) CHECK(LEN(LTRIM(Name)) > 0) UNIQUE NOT NULL
);

GO

CREATE TABLE Departaments(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    Financing MONEY CHECK(Financing > 0) DEFAULT(0) NOT NULL,
    Name NVARCHAR(100) CHECK(LEN(LTRIM(Name)) > 0) UNIQUE NOT NULL,
    FacultyId INT FOREIGN KEY REFERENCES Faculties(Id) NOT NULL
);

GO

CREATE TABLE Teachers(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    Name NVARCHAR(100) CHECK(LEN(LTRIM(Name)) > 0) UNIQUE NOT NULL,
    Surname NVARCHAR(100) CHECK(LEN(LTRIM(Surname)) > 0) UNIQUE NOT NULL,
    Salary MONEY CHECK(Salary > 0) NOT NULL
);

GO

CREATE TABLE Subjects(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    Name NVARCHAR(100) CHECK(LEN(LTRIM(Name)) > 0) UNIQUE NOT NULL
)

GO

CREATE TABLE Groups(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    Name NVARCHAR(100) CHECK(LEN(LTRIM(Name)) > 0) UNIQUE NOT NULL,
    Year INT CHECK(Year >= 1 AND Year <= 5) NOT NULL,
    DepartamentId INT FOREIGN KEY REFERENCES Departaments(Id)
);

GO 

CREATE TABLE Lectures(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    DayOfWeek INT CHECK(DayOfWeek >= 1 AND DayOfWeek <= 7) NOT NULL,
    LectureRoom NVARCHAR(MAX) CHECK(LEN(LTRIM(LectureRoom)) > 0) NOT NULL,
    SubjectId INT FOREIGN KEY REFERENCES Subjects(Id) NOT NULL,
    TeacherId INT FOREIGN KEY REFERENCES Teachers(Id) NOT NULL
);

GO 

CREATE TABLE GroupLecture(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    GroupId INT FOREIGN KEY REFERENCES Groups(Id) NOT NULL,
    LectureId INT FOREIGN KEY REFERENCES  Lectures(Id) NOT NULL
);

GO
