CREATE DATABASE Academy;

GO

USE Academy;

GO 

CREATE TABLE Teachers(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    Name NVARCHAR(255) CHECK(LEN(LTRIM(Name)) > 0) NOT NULL,
    Surname NVARCHAR(255) CHECK(LEN(LTRIM(Surname)) > 0) NOT NULL
);

CREATE TABLE Assistants( 
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    TeacherId INT FOREIGN KEY REFERENCES Teachers(Id) NOT NULL
);

CREATE TABLE Curators(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    TeacherId INT FOREIGN KEY REFERENCES Teachers(Id) NOT NULL
);

CREATE TABLE Deans(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    TeacherId INT FOREIGN KEY REFERENCES Teachers(Id) NOT NULL
);

CREATE TABLE Faculties(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    Building INT CHECK(Building BETWEEN 1 AND 5) NOT NULL,
    Name NVARCHAR(100) CHECK(LEN(LTRIM(Name)) > 0) NOT NULL,
    DeanId INT FOREIGN KEY REFERENCES Deans(Id) NOT NULL
);

CREATE TABLE Subjects(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    Name NVARCHAR(100) CHECK(LEN(LTRIM(Name)) > 0) NOT NULL
);

CREATE TABLE Lectures(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    SubjectId INT FOREIGN KEY REFERENCES Subjects(Id),
    TeacherId INT FOREIGN KEY REFERENCES Teachers(Id)
);

CREATE TABLE LectureRooms(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    Building INT CHECK(Building BETWEEN 1 AND 5) NOT NULL,
    Name NVARCHAR(10) CHECK(LEN(LTRIM(Name)) > 0) NOT NULL
);

CREATE TABLE Schedules(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    Class INT CHECK(Class BETWEEN 1 AND 8) NOT NULL,
    DayOfWeek INT CHECK(DayOfWeek BETWEEN 1 AND 7) NOT NULL,
    Week INT CHECK(Week BETWEEN 1 AND 52) NOT NULL,
    LectureId INT FOREIGN KEY REFERENCES Lectures(Id),
    LectureRooms INT FOREIGN KEY REFERENCES LectureRooms(Id)
);

CREATE TABLE Heads(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    TeacherId INT FOREIGN KEY REFERENCES Teachers(Id)
);

CREATE TABLE Departaments(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    Building INT CHECK(Building BETWEEN 1 AND 5) NOT NULL,
    Name NVARCHAR(100) CHECK(LEN(LTRIM(Name)) > 0) NOT NULL,
    FacultyId INT FOREIGN KEY REFERENCES Faculties(Id) NOT NULL,
    HeadId INT FOREIGN KEY REFERENCES Heads(Id) NOT NULL
)

CREATE TABLE Groups(
    Id INT PRIMARY KEY IDENTITY(1,1) Not NULL,
    Name NVARCHAR(10) CHECK(LEN(LTRIM(Name)) > 0) NOT NULL,
    Year INT CHECK(Year BETWEEN 1 AND 5) NOT NULL,
    DepartmentId INT FOREIGN KEY REFERENCES Departaments(Id) NOT NULL
);

CREATE TABLE GroupsLectures(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    GroupId INT FOREIGN KEY REFERENCES Groups(Id) NOT NULL,
    LectureId INT FOREIGN KEY REFERENCES Lectures(Id) NOT NULL
);

CREATE TABLE GroupsCurators(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    CuratorId INT FOREIGN KEY REFERENCES Curators(Id) NOT NULL,
    GroupId INT FOREIGN KEY REFERENCES Groups(Id) NOT NULL
);

GO