CREATE DATABASE Academy;

GO 

USE Academy;

GO

CREATE TABLE Curators(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    Name NVARCHAR(100) CHECK(LEN(LTRIM(Name)) > 0) NOT NULL,
    Surname NVARCHAR(100) CHECK(LEN(LTRIM(Surname)) > 0) NOT NULL
);

GO

CREATE TABLE Faculties(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    Name NVARCHAR(100) CHECK(LEN(LTRIM(Name)) > 0) UNIQUE NOT NULL
);

GO

CREATE TABLE Departaments(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    Building INT CHECK(Building >= 1 AND Building <= 5) NOT NULL,
    Financing MONEY CHECK(Financing > 0) DEFAULT(0) NOT NULL,
    Name NVARCHAR(100) CHECK(LEN(LTRIM(Name)) > 0) UNIQUE NOT NULL,
    FacultyId INT FOREIGN KEY REFERENCES Faculties(Id) NOT NULL
);

GO

CREATE TABLE Groups(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    Name NVARCHAR(100) CHECK(LEN(LTRIM(Name)) > 0) UNIQUE NOT NULL,
    Year INT CHECK(Year >= 1 AND Year <= 5) NOT NULL,
    DepartamentId INT FOREIGN KEY REFERENCES Departaments(Id) NOT NULL
);

GO

CREATE TABLE GroupsCurators(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    GroupId INT FOREIGN KEY REFERENCES Groups(Id) NOT NULL,
    CuratorId INT FOREIGN KEY REFERENCES Curators(Id) NOT NULL
 );

 GO

 CREATE TABLE Subjects(
    Id int PRIMARY KEY IDENTITY(1,1) NOT NULL,
    Name NVARCHAR(100) CHECK(LEN(LTRIM(Name)) > 0) UNIQUE NOT NULL
 );

 GO 

 CREATE TABLE Students(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    Name NVARCHAR(100) CHECK(LEN(LTRIM(Name)) > 0) NOT NULL,
    Surname NVARCHAR(100) CHECK(LEN(LTRIM(Surname)) > 0) NOT NULL,
    Raiting INT CHECK(Raiting >= 1 AND Raiting <= 5) NOT NULL
 );

 GO 

 CREATE TABLE Teachers(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    Name NVARCHAR(100) CHECK(LEN(LTRIM(Name)) > 0) NOT NULL,
    Surname NVARCHAR(100) CHECK(LEN(LTRIM(Surname)) > 0) NOT NULL,
    IsProfesor BIT DEFAULT(0) NOT NULL,
    Salary MONEY CHECK(Salary > 0) NOT NULL
 );

 GO

 CREATE TABLE Lectures(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    Date DATE CHECK(Date < GETDATE()) NOT NULL,
    SubjectId INT FOREIGN KEY REFERENCES Subjects(Id) NOT NULL,
    TeacherId INT FOREIGN KEY REFERENCES Teachers(Id) NOT NULL
 );

 GO

 CREATE TABLE GroupsLecture(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    GroupId INT FOREIGN KEY REFERENCES Groups(Id) NOT NULL,
    LectureId INT FOREIGN KEY REFERENCES Lectures(Id) NOT NULL
 );

 GO 

 CREATE TABLE GroupsStudents(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    GroupId INT FOREIGN KEY REFERENCES Groups(Id) NOT NULL,
    StudentId INT FOREIGN KEY REFERENCES Students(Id) NOT NULL
 );

 GO
