CREATE DATABASE SportShopDB;

GO 

USE SportShopDB;

GO

CREATE TABLE Positions(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    Name NVARCHAR(50) CHECK(LEN(LTRIM(Name)) > 0) NOT NULL
);

CREATE TABLE Employees(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    FullName NVARCHAR(255) CHECK(LEN(LTRIM(FullName)) > 0) NOT NULL,
    PositionId INT FOREIGN KEY REFERENCES Positions(Id) NOT NULL,
    HireDate DATE CHECK(HireDate > '2020-01-01') NOT NULL,
    Sex BIT NOT NULL,
    Salary MONEY CHECK(Salary >= 0) NOT NULL
);

CREATE TABLE Categories(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    Name NVARCHAR(50) CHECK(LEN(LTRIM(Name)) > 0) NOT NULL
);

CREATE TABLE Producers(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    Name NVARCHAR(50) CHECK(LEN(LTRIM(Name)) > 0) NOT NULL
);

CREATE TABLE Products(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    Name NVARCHAR(255) CHECK(LEN(LTRIM(Name)) > 0) NOT NULL,
    Quantity INT CHECK(Quantity >= 0) DEFAULT(0) NOT NULL,
    CategoryId INT FOREIGN KEY REFERENCES Categories(Id) NOT NULL,
    ProducerId INT FOREIGN KEY REFERENCES Producers(Id) NOT NULL,
    Cost MONEY CHECK(Cost >= 0) DEFAULT(0) NOT NULL,
    Price MONEY CHECK(Price >= 0) DEFAULT(0) NOT NULL
);

CREATE TABLE Customers(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    FullName NVARCHAR(255) CHECK(LEN(LTRIM(FullName)) > 0) NOT NULL,
    Email NVARCHAR(255) CHECK (Email LIKE '%@%.%') UNIQUE NOT NULL,
    PhoneNumber NVARCHAR(20) CHECK(PhoneNumber LIKE '+%' AND LEN(PhoneNumber) BETWEEN 12 AND 20) UNIQUE NOT NULL,
    Sex BIT NOT NULL,
    Discount INT CHECK(Discount BETWEEN 0 AND 100) DEFAULT(0),
    MailingSub BIT DEFAULT(0)
);

CREATE TABLE Orders(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    CustomerId INT FOREIGN KEY REFERENCES Customers(Id),
    EmployeeId INT FOREIGN KEY REFERENCES Employees(Id) NOT NULL,
    SaleDate DATETIME CHECK(SaleDate > '2020-01-01') DEFAULT(GETDATE()) NOT NULL
);

CREATE TABLE OrderItem(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    ProductId INT FOREIGN KEY REFERENCES Products(Id) NOT NULL,
    Quantity INT CHECK(Quantity > 0) NOT NULL,
    UnitPrice MONEY CHECK(UnitPrice > 0) NOT NULL,
    OrderId INT FOREIGN KEY REFERENCES Orders(Id) NOT NULL
);

CREATE TABLE EmployeeArchive(
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    FullName NVARCHAR(255) CHECK(LEN(LTRIM(FullName)) > 0) NOT NULL,
    Sex BIT NOT NULL,
    Salary MONEY CHECK(Salary >= 0) NOT NULL,
    PositionId INT FOREIGN KEY REFERENCES Positions(Id) NOT NULL,
    HireDate DATE CHECK(HireDate > '2020-01-01') NOT NULL,
    FireDate DATE DEFAULT(GETDATE())
);

GO
